import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/lib/fonts";
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/common/navbar";

export const metadata: Metadata = {
  title: "  Reserve Pro  | Mariano Romero",
  description: "Generated by mariano Romero",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
